<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ config('app.name', 'Shadi') }} - Biodata PDF</title>
    <style>
        body {
            font-family: DejaVu Sans, Helvetica, Arial, sans-serif;
            background: #f8fafc;
            color: #0f172a;
            margin: 0;
            padding: 0;
        }
        .wrapper {
            width: 100%;
            padding: 20px;
        }
        .sheet {
            width: 100%;
            max-width: 800px;
            margin: 0 auto;
            background: #ffffff;
            border: 1px solid #e5e7eb;
            border-radius: 12px;
            padding: 20px;
        }
        .header {
            width: 100%;
            margin-bottom: 16px;
            border-bottom: 1px solid #e5e7eb;
            padding-bottom: 12px;
        }
        .header-table {
            width: 100%;
            border-collapse: collapse;
        }
        .header-table td {
            vertical-align: top;
            padding: 4px;
        }
        .photo {
            width: 130px;
            height: 130px;
            border-radius: 12px;
            object-fit: cover;
            border: 2px solid #e5e7eb;
        }
        .title {
            font-size: 22px;
            margin: 0 0 6px 0;
        }
        .subtitle {
            font-size: 12px;
            color: #6b7280;
            margin: 0 0 4px 0;
        }
        .section {
            margin-bottom: 14px;
        }
        .section-title {
            font-size: 14px;
            text-transform: uppercase;
            color: #0f172a;
            letter-spacing: 0.5px;
            margin: 0 0 8px 0;
        }
        .info-table {
            width: 100%;
            border-collapse: collapse;
        }
        .info-table td {
            padding: 6px 8px;
            border: 1px solid #e5e7eb;
            font-size: 12px;
        }
        .info-label {
            width: 35%;
            background: #f8fafc;
            color: #475569;
            font-weight: 600;
        }
        .info-value {
            color: #111827;
        }
        .about {
            border: 1px solid #e5e7eb;
            padding: 10px;
            border-radius: 8px;
            font-size: 12px;
            color: #111827;
            line-height: 1.5;
        }
        .footer {
            margin-top: 10px;
            text-align: right;
            font-size: 11px;
            color: #6b7280;
        }
    </style>
</head>
<body>
    <div class="wrapper">
        <div class="sheet">
            <div class="header">
                <table class="header-table">
                    <tr>
                        <td style="width: 140px;">
                            @if($photoUrl)
                                <img src="{{ $photoUrl }}" alt="{{ $user->name }}" class="photo">
                            @endif
                        </td>
                        <td>
                            <h1 class="title">{{ $user->name }}</h1>
                            <p class="subtitle">Profile ID: {{ $user->id }}</p>
                            <p class="subtitle">
                                {{ $user->getAge() ? $user->getAge() . ' years' : 'Age not set' }} &middot; {{ ucfirst($user->gender) }}
                            </p>
                            <p class="subtitle">Generated by {{ config('app.name', 'Shadi') }}</p>
                        </td>
                    </tr>
                </table>
            </div>

            <div class="section">
                <h3 class="section-title">Basic Details</h3>
                <table class="info-table">
                    <tr>
                        <td class="info-label">Marital Status</td>
                        <td class="info-value">{{ $profile?->getMaritalStatusLabel() ?? 'Not set' }}</td>
                    </tr>
                    <tr>
                        <td class="info-label">Height</td>
                        <td class="info-value">{{ $profile?->getHeightInFeet() ?? ($profile?->height ? $profile->height . ' cm' : 'Not set') }}</td>
                    </tr>
                    <tr>
                        <td class="info-label">Mother Tongue</td>
                        <td class="info-value">{{ $profile?->motherTongue?->name ?? 'Not set' }}</td>
                    </tr>
                    <tr>
                        <td class="info-label">Religion / Caste</td>
                        <td class="info-value">
                            {{ $profile?->religion?->name ?? 'Not set' }} @if($profile?->caste?->name) / {{ $profile->caste->name }} @endif
                        </td>
                    </tr>
                </table>
            </div>

            <div class="section">
                <h3 class="section-title">Location</h3>
                <table class="info-table">
                    <tr>
                        <td class="info-label">Country</td>
                        <td class="info-value">{{ $profile?->country?->name ?? 'Not set' }}</td>
                    </tr>
                    <tr>
                        <td class="info-label">State</td>
                        <td class="info-value">{{ $profile?->state?->name ?? 'Not set' }}</td>
                    </tr>
                    <tr>
                        <td class="info-label">City</td>
                        <td class="info-value">{{ $profile?->city?->name ?? 'Not set' }}</td>
                    </tr>
                </table>
            </div>

            <div class="section">
                <h3 class="section-title">Education & Career</h3>
                <table class="info-table">
                    <tr>
                        <td class="info-label">Education</td>
                        <td class="info-value">{{ $profile?->education?->name ?? 'Not set' }}</td>
                    </tr>
                    <tr>
                        <td class="info-label">Occupation</td>
                        <td class="info-value">{{ $profile?->occupation?->name ?? 'Not set' }}</td>
                    </tr>
                    <tr>
                        <td class="info-label">Annual Income</td>
                        <td class="info-value">{{ $profile?->annual_income ? $profile->annual_income : 'Not set' }}</td>
                    </tr>
                    <tr>
                        <td class="info-label">Employer</td>
                        <td class="info-value">{{ $profile?->employer_name ?? 'Not set' }}</td>
                    </tr>
                </table>
            </div>

            <div class="section">
                <h3 class="section-title">Family Details</h3>
                <table class="info-table">
                    <tr>
                        <td class="info-label">Family Type</td>
                        <td class="info-value">{{ $profile?->family_type ?? 'Not set' }}</td>
                    </tr>
                    <tr>
                        <td class="info-label">Family Status</td>
                        <td class="info-value">{{ $profile?->family_status ?? 'Not set' }}</td>
                    </tr>
                    <tr>
                        <td class="info-label">Father's Occupation</td>
                        <td class="info-value">{{ $profile?->father_occupation ?? 'Not set' }}</td>
                    </tr>
                    <tr>
                        <td class="info-label">Mother's Occupation</td>
                        <td class="info-value">{{ $profile?->mother_occupation ?? 'Not set' }}</td>
                    </tr>
                </table>
            </div>

            <div class="section">
                <h3 class="section-title">Partner Preferences</h3>
                <table class="info-table">
                    <tr>
                        <td class="info-label">Preferred Age</td>
                        <td class="info-value">
                            @if($profile?->partner_age_min && $profile?->partner_age_max)
                                {{ $profile->partner_age_min }} - {{ $profile->partner_age_max }} years
                            @else
                                Not set
                            @endif
                        </td>
                    </tr>
                    <tr>
                        <td class="info-label">Preferred Height</td>
                        <td class="info-value">
                            @if($profile?->partner_height_min && $profile?->partner_height_max)
                                {{ $profile->partner_height_min }} - {{ $profile->partner_height_max }} cm
                            @else
                                Not set
                            @endif
                        </td>
                    </tr>
                    <tr>
                        <td class="info-label">Preferred Religion</td>
                        <td class="info-value">{{ $profile?->partner_religion ?? 'Not set' }}</td>
                    </tr>
                    <tr>
                        <td class="info-label">Preferred Caste</td>
                        <td class="info-value">{{ $profile?->partner_caste ?? 'Not set' }}</td>
                    </tr>
                    <tr>
                        <td class="info-label">Preferred Education</td>
                        <td class="info-value">{{ $profile?->partner_education ?? 'Not set' }}</td>
                    </tr>
                    <tr>
                        <td class="info-label">Preferred Occupation</td>
                        <td class="info-value">{{ $profile?->partner_occupation ?? 'Not set' }}</td>
                    </tr>
                    <tr>
                        <td class="info-label">Preferred Country</td>
                        <td class="info-value">{{ $profile?->partner_country ?? 'Not set' }}</td>
                    </tr>
                    <tr>
                        <td class="info-label">Expectations</td>
                        <td class="info-value">{{ $profile?->partner_expectations ?? 'Not set' }}</td>
                    </tr>
                </table>
            </div>

            <div class="section">
                <h3 class="section-title">About Me</h3>
                <div class="about">
                    {{ $profile?->about_me ?? 'No bio added yet.' }}
                </div>
            </div>

            <div class="footer">
                Downloaded on {{ now()->format('d M Y, h:i A') }} &middot; {{ config('app.name', 'Shadi') }}
            </div>
        </div>
    </div>
</body>
</html>


