<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ config('app.name', 'Shadi') }} - Biodata</title>
    <style>
        body {
            font-family: 'Helvetica Neue', Arial, sans-serif;
            background: #f7f7f7;
            color: #333;
            margin: 0;
            padding: 24px;
        }
        .sheet {
            background: #fff;
            max-width: 900px;
            margin: 0 auto;
            padding: 24px;
            border: 1px solid #e5e7eb;
            border-radius: 12px;
            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.05);
        }
        .header {
            display: flex;
            gap: 16px;
            align-items: center;
            border-bottom: 1px solid #e5e7eb;
            padding-bottom: 16px;
            margin-bottom: 20px;
        }
        .header img {
            width: 120px;
            height: 120px;
            border-radius: 12px;
            object-fit: cover;
            border: 2px solid #e5e7eb;
        }
        .title {
            font-size: 24px;
            margin: 0 0 4px 0;
            color: #111827;
        }
        .subtitle {
            margin: 0;
            color: #6b7280;
            font-size: 14px;
        }
        .section {
            margin-bottom: 18px;
        }
        .section h3 {
            margin: 0 0 8px 0;
            font-size: 16px;
            color: #0f172a;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }
        .grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
            gap: 8px 16px;
        }
        .field {
            display: flex;
            gap: 6px;
            align-items: baseline;
        }
        .label {
            color: #6b7280;
            min-width: 120px;
            font-size: 13px;
        }
        .value {
            color: #111827;
            font-weight: 600;
            font-size: 14px;
        }
        .footer {
            margin-top: 16px;
            padding-top: 12px;
            border-top: 1px solid #e5e7eb;
            font-size: 12px;
            color: #6b7280;
            text-align: right;
        }
    </style>
</head>
<body>
    <div class="sheet">
        <div class="header">
            @if($photoUrl)
                <img src="{{ $photoUrl }}" alt="{{ $user->name }}">
            @endif
            <div>
                <h1 class="title">{{ $user->name }}</h1>
                <p class="subtitle">
                    Profile ID: {{ $user->id }} &middot; {{ $user->getAge() ? $user->getAge() . ' years' : 'Age not set' }}
                </p>
                <p class="subtitle">Generated by {{ config('app.name', 'Shadi') }}</p>
            </div>
        </div>

        <div class="section">
            <h3>Basic Details</h3>
            <div class="grid">
                <div class="field"><span class="label">Gender</span><span class="value">{{ ucfirst($user->gender) }}</span></div>
                <div class="field"><span class="label">Marital Status</span><span class="value">{{ $profile?->getMaritalStatusLabel() ?? 'Not set' }}</span></div>
                <div class="field"><span class="label">Height</span><span class="value">{{ $profile?->getHeightInFeet() ?? ($profile?->height ? $profile->height . ' cm' : 'Not set') }}</span></div>
                <div class="field"><span class="label">Mother Tongue</span><span class="value">{{ $profile?->motherTongue?->name ?? 'Not set' }}</span></div>
                <div class="field"><span class="label">Religion</span><span class="value">{{ $profile?->religion?->name ?? 'Not set' }}</span></div>
                <div class="field"><span class="label">Caste</span><span class="value">{{ $profile?->caste?->name ?? 'Not set' }}</span></div>
            </div>
        </div>

        <div class="section">
            <h3>Location</h3>
            <div class="grid">
                <div class="field"><span class="label">Country</span><span class="value">{{ $profile?->country?->name ?? 'Not set' }}</span></div>
                <div class="field"><span class="label">State</span><span class="value">{{ $profile?->state?->name ?? 'Not set' }}</span></div>
                <div class="field"><span class="label">City</span><span class="value">{{ $profile?->city?->name ?? 'Not set' }}</span></div>
            </div>
        </div>

        <div class="section">
            <h3>Education & Career</h3>
            <div class="grid">
                <div class="field"><span class="label">Education</span><span class="value">{{ $profile?->education?->name ?? 'Not set' }}</span></div>
                <div class="field"><span class="label">Occupation</span><span class="value">{{ $profile?->occupation?->name ?? 'Not set' }}</span></div>
                <div class="field"><span class="label">Annual Income</span><span class="value">{{ $profile?->annual_income ? $profile->annual_income : 'Not set' }}</span></div>
                <div class="field"><span class="label">Employer</span><span class="value">{{ $profile?->employer_name ?? 'Not set' }}</span></div>
            </div>
        </div>

        <div class="section">
            <h3>Family Details</h3>
            <div class="grid">
                <div class="field"><span class="label">Family Type</span><span class="value">{{ $profile?->family_type ?? 'Not set' }}</span></div>
                <div class="field"><span class="label">Family Status</span><span class="value">{{ $profile?->family_status ?? 'Not set' }}</span></div>
                <div class="field"><span class="label">Father's Occupation</span><span class="value">{{ $profile?->father_occupation ?? 'Not set' }}</span></div>
                <div class="field"><span class="label">Mother's Occupation</span><span class="value">{{ $profile?->mother_occupation ?? 'Not set' }}</span></div>
            </div>
        </div>

        <div class="section">
            <h3>Partner Preferences</h3>
            <div class="grid">
                <div class="field"><span class="label">Preferred Age</span><span class="value">
                    @if($profile?->partner_age_min && $profile?->partner_age_max)
                        {{ $profile->partner_age_min }} - {{ $profile->partner_age_max }} years
                    @else
                        Not set
                    @endif
                </span></div>
                <div class="field"><span class="label">Preferred Height</span><span class="value">
                    @if($profile?->partner_height_min && $profile?->partner_height_max)
                        {{ $profile->partner_height_min }} - {{ $profile->partner_height_max }} cm
                    @else
                        Not set
                    @endif
                </span></div>
                <div class="field"><span class="label">Preferred Religion</span><span class="value">{{ $profile?->partner_religion ?? 'Not set' }}</span></div>
                <div class="field"><span class="label">Preferred Caste</span><span class="value">{{ $profile?->partner_caste ?? 'Not set' }}</span></div>
                <div class="field"><span class="label">Preferred Education</span><span class="value">{{ $profile?->partner_education ?? 'Not set' }}</span></div>
                <div class="field"><span class="label">Preferred Occupation</span><span class="value">{{ $profile?->partner_occupation ?? 'Not set' }}</span></div>
                <div class="field"><span class="label">Preferred Country</span><span class="value">{{ $profile?->partner_country ?? 'Not set' }}</span></div>
                <div class="field"><span class="label">Expectations</span><span class="value">{{ $profile?->partner_expectations ?? 'Not set' }}</span></div>
            </div>
        </div>

        <div class="section">
            <h3>About Me</h3>
            <p style="margin: 0; line-height: 1.6; color: #374151;">
                {{ $profile?->about_me ?? 'No bio added yet.' }}
            </p>
        </div>

        <div class="footer">
            Downloaded on {{ now()->format('d M Y, h:i A') }} &middot; {{ config('app.name', 'Shadi') }}
        </div>
    </div>
</body>
</html>

